### ISSUE TITLE
aggiungere la possbililità di utilizzare un css custom sul template standard

### ISSUE THREAD

**Issue by chiaragdl** [istricesrl/glisweb#1]
Sarebbe comodo poter utilizzare un css diverso da quello standard con i template standard

**Comment by fabiomosti** [comment]
sì mi sembra un'ottima idea, avevamo già pensato di implementare questa funzione chiamando "temi" i CSS custom da associare ai template, si potrebbe estendere il meccanismo e consentire di associare diversi "temi" a ciascun template!
