### ISSUE TITLE
correggere script per generazione database

### ISSUE THREAD

**Issue by silvia-df** [istricesrl/glisweb#105]
modificare il file "_gw.mysql.install.sh"

    read -p "vuoi assegnare il database a un utente specifico (s/n)? " YN

    if [ $YN == "s" ]; then

        read -p "l'utente va creato (s/n)? " SYN

        read -p "nome utente DATABASE: " SRVDBUSER

        if [ $SYN == "s" ]; then
            read -p "password utente DATABASE: " SRVDBPASS
            mysql -h $SRVADDR -u $SRVUSER $PASSC -e "CREATE USER \`$SRVDBUSER\`@\`%\` IDENTIFIED BY '$SRVDBPASS';"
        fi

        mysql -h $SRVADDR -u $SRVUSER $PASSC -e "GRANT ALL PRIVILEGES ON \`$SRVDBNAME\`.* TO \`$SRVDBUSER\`@\`%\`;"

    fi

**Comment by fabiomosti** [comment]
fatto :smile:
