### ISSUE TITLE
controllo backurl del 'no' della delete 

### ISSUE THREAD

**Issue by chiaragdl** [istricesrl/glisweb#126]
al momento della cancellazione di un'entità se si fa clic su 'no' per annullare la cancellazione non si ritorna sull'entità che si voleva cancellare ma sulla view 
(se cerco di cancellare Mario Rossi e poi faccio clic su no vengo riportata alla view anagrafica anzichè al form di gestione di MArio Rossi)

**Comment by fabiomosti** [comment]
corretto in feature/cancellazione-righe-subform
