### ISSUE TITLE
proteggere l'inserimento delle password negli script

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#149]
negli script in _src/_sh/ utilizzare l'opzione -s di read ogni volta che si richiede all'utente l'inserimento di una password; in particolare si noti che questo va fatto in maniera dinamica per lo script _gw.config.sh che effettua le read in base ai placeholder letti dal modello di partenza

dove invece la read è utilizzata normalmente non dovrebbero sorgere problemi

bisogna passare ad es. da questo:

    read -p "password utente AMMINISTRATORE: " SRVPASS

a questo:

    read -s -p "password utente AMMINISTRATORE: " SRVPASS && echo

**Comment by fabiomosti** [comment]
@chiaragdl @silvia-df se notate qualche comportamento anomalo negli script _gw.mysql.*.sh segnalatemelo
se avete voglia e tempo testate lo script _gw.config.sh che è una figata!!!

**Comment by chiaragdl** [comment]
l'ho testato sia sul mio pc sia su quello in ufficio per configurare glisweb in locale ed effettivamente è meraviglioso <3 (ho provato solo la versione base)

**Comment by fabiomosti** [comment]
perfetto segno come fatto :slightly_smiling_face:
