### ISSUE TITLE
includere nel ciclo di release la creazione dello schema e l'aggiunta dei dati al database

### ISSUE THREAD

**Issue by chiaragdl** [istricesrl/glisweb#36]

**Comment by fabiomosti** [comment]
@chiaragdl @silvia-df questa issue è resa obsoleta dal sistema di patch? perché l'avevamo aperta?

**Comment by fabiomosti** [comment]
ok fatto, è nel build.xml della distribuzione generale del framework su dol-amroth
la distribuzione viene fatta su develop via git su un clone locale del repository
