### ISSUE TITLE
aggiungere la possibilità di definire il colore e stile delle selectbox dal css 

### ISSUE THREAD

**Issue by chiaragdl** [istricesrl/glisweb#37]
nel js della selectbox anziché attribuire all'oggetto il colore sarebbe meglio attribuirgli una classe in modo da poter modificarne lo stile nel css

**Comment by fabiomosti** [comment]
@chiaragdl fatto, le due classi sono in _selectbox.css e sono:

`.combobox-base-background {
    background-color: #ffffff !important;
}

.combobox-active-background {
    background-color: #eeeeee !important;
}
`

**Comment by fabiomosti** [comment]
@chiaragdl se riesci a usarle per mettere lo sfondo verde nel tema verde, puoi chiudere la issue

**Comment by chiaragdl** [comment]
si perfetto funziona, creando il fil selectbox.css è possibile scegliere il colore custom della selectbox
