### ISSUE TITLE
eliminare l'alone blu attorno ai campi col focus

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#46]
@chiaragdl tu sai come si fa :smile:

**Comment by chiaragdl** [comment]
questo è il codice

.form-control:focus {
    border-color: #464945;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(68, 71, 67, 0.6);
  }

**Comment by fabiomosti** [comment]
risolto in feature/cancellazione-righe-subform
