### ISSUE TITLE
le categorie prodotti vengono inserite ma non visualizzate nella view

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#58]
https://glisweb.istricesrl.it/catalogo/categorie.it-IT.html

**Comment by fabiomosti** [comment]
@silvia-df @chiaragdl è un problema di view

**Comment by chiaragdl** [comment]
@silvia-df 
RISOLTO: nella view era presente la riga "INNER JOIN tipologie_pubblicazione ON tipologie_pubblicazione.id = categorie_prodotti.id_tipologia_pubblicazione"
che bloccava la generazione della view
modificata INNER JOIN in LEFT JOIN
create patch e aggiornato script
