### ISSUE TITLE
colonne mancanti alle tabelle task e job

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#63]
alla tabella task sembra mancare la colonna iterazioni, e a entrambe sembra mancare la colonna delay, @chiaragdl puoi verificare?

**Comment by chiaragdl** [comment]
sì non ci sono... vanno aggiunte? entrambe int?

**Comment by chiaragdl** [comment]
aggiunti campi delay in cron e job, create patch e aggiornati script

**Comment by fabiomosti** [comment]
ok chiudo la issue
