### ISSUE TITLE
togliere la tipologia dalla form indirizzi

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#88]
http://localhost/archivio/indirizzi/gestione.it-IT.html

**Comment by fabiomosti** [comment]
@silvia-df l'hai fatto tu? :sweat_smile:

**Comment by silvia-df** [comment]
No non mi sembra di aver fatto modifiche alla gestione indirizzi, ho lavorato solo all'associazione tra indirizzi e anagrafiche nella "http://localhost/anagrafica/gestione.it-IT.html" dove ho modificato la tendina della tipologia indirizzo togliendo l'icona e mettendo la tipologia per esteso

**Comment by fabiomosti** [comment]
sembra a posto comunque
