### ISSUE TITLE
reimplementare scalatore immagini

### ISSUE THREAD

**Issue by fabiomosti** [istricesrl/glisweb#92]
@silvia-df qui ho bisogno di te xD l'avevamo fatto assieme, probabilmente è una cosa rapida

**Comment by silvia-df** [comment]
@fabiomosti ok perfetto, quando vuoi

**Comment by fabiomosti** [comment]
love :smile: io oggi sono qua, dimmi tu!

**Comment by fabiomosti** [comment]
reimplementata con successo
